- hosts: raspberry-pis
  vars:
    root_dir: /home/pi/apps/dashboard
    service_name: dashboard
  tasks:
    - name: packages
      apt: name='{{ item }}' state=present
      with_items:
        - git
        - virtualenv
      sudo: yes
    - name: code
      synchronize: src=../ dest={{ root_dir }}
    - name: virtualenv
      command: virtualenv {{ root_dir }}/venv -p python3 creates={{ root_dir }}/venv
    - name: dependencies
      pip: requirements={{ root_dir }}/requirements.txt virtualenv={{ root_dir }}/venv
    - name: service
      template: src={{ service_name }}.service dest=/etc/systemd/system/{{ service_name }}.service
      sudo: yes
    - name: server
      service: name={{ service_name }} state=restarted enabled=yes
      sudo: yes
