- hosts: raspberry-pis
  vars:
    root_dir: /home/pi/apps/dashboard
    dns_service_name: dyndns
    web_service_name: dashboard
    io_service_name: circuits
  tasks:
    - name: packages
      apt: name='{{ item }}' state=present
      with_items:
        - git
        - virtualenv
      sudo: yes
    - name: code
      synchronize: src=../ dest={{ root_dir }}
    - name: virtualenv
      command: virtualenv {{ root_dir }}/venv -p python3 creates={{ root_dir }}/venv
    - name: dependencies
      pip: requirements={{ root_dir }}/requirements.txt virtualenv={{ root_dir }}/venv
    - name: web service
      template: src={{ web_service_name }}.service dest=/etc/systemd/system/{{ web_service_name }}.service
      sudo: yes
    - name: io service
      template: src={{ io_service_name }}.service dest=/etc/systemd/system/{{ io_service_name }}.service
      sudo: yes
    - name: dns service
      template: src={{ dns_service_name }}.service dest=/etc/systemd/system/{{ dns_service_name }}.service
      sudo: yes
    - name: start web service
      service: name={{ web_service_name }} state=restarted enabled=yes
      sudo: yes
    - name: start io service
      service: name={{ io_service_name }} state=restarted enabled=yes
      sudo: yes
    - name: start dns service
      service: name={{ dns_service_name }} state=restarted enabled=yes
      sudo: yes
